service: graphql-apolloclient

provider:
  name: aws
  runtime: nodejs12.x

functions:
  graphql:
    handler: handler.server
    events:
    - http:
        path: /graphql
        method: post
        cors: true
        
  playground:
    handler: handler.playground
    events:
    - http:
        path: /graphql
        method: get
        cors: true