service: tableexample


plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  environment:
    TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
          - dynamodb:Query
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:service}-${opt:stage, self:provider.stage}'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: /

resources:
  Resources:
      productsTable:
          Type: AWS::DynamoDB::Table
          Properties:
              TableName: ${self:service}-${opt:stage, self:provider.stage}
              AttributeDefinitions:
                  - AttributeName: PK
                    AttributeType: S
              KeySchema:
                  - AttributeName: PK
                    KeyType: HASH
              BillingMode: PAY_PER_REQUEST